# configs/config.yaml
log:
  level: "debug" # 可選值: debug, info, warn, error
  format: "json" # 可選值: json, console
  file_path: "logs/game.log" # 日誌檔案路徑，為空則只輸出到控制台

server:
  game:
    port: "9090"
  admin:
    port: "6060"

data:
  master_database:
    driver: "postgres"
    host: "localhost"
    port: 5432
    user: "user"
    password: "password"
    dbname: "fish_db"
    sslmode: "disable"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

jwt:
  secret: "your-super-secret-key" # 務必修改成一個複雜的密鑰
  issuer: "fish_server" # token 發行者
  expire: 7200 # token 過期時間，單位為秒 (例如 7200 表示 2 小時)